#:kivy 1.0.9

<Label>:
    markup: True
    color: 0,0,0,1  # This defaults to 1,1,1,1 when not used

<Root>:

    orientation: 'horizontal'
    RecordButton:

        id: record_button
        background_normal: "background1.jpg"
        background_down: "background1.jpg"
        font_size:30
        text: '[color=EC674A]Order, Please![/color]'


        on_release: 
            self.record()




        
